version: 2.1
commands:
  install_gems:
    steps:
      - restore_cache:
          key: fluent-plugin-gelf2-{{ checksum "fluent-plugin-gelf.gemspec" }}-{{ checksum "Gemfile" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --full-index
      - save_cache:
          key: fluent-plugin-gelf2-{{ checksum "fluent-plugin-gelf.gemspec" }}-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
executors:
  ruby:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/ruby:<< parameters.version >>
    working_directory: ~/fluent-plugin-gelf
jobs:
  publish:
    executor: ruby
    steps:
      - checkout
      - install_gems
      - run:
          name: Configure RubyGems API key
          command: |
            mkdir -p ~/.gem
            echo ":rubygems_api_key: $RUBYGEMS_API_KEY" >  ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
      - run:
          name: Build gem
          command: bundle exec rake build --trace
      - run:
          name: Release gem
          command: bundle exec rake release:rubygem_push --trace
  rubocop:
    executor: ruby
    steps:
      - checkout
      - install_gems
      - run:
          name: Run RuboCop
          command: bundle exec rake rubocop --trace
  test:
    executor: ruby
    steps:
      - checkout
      - install_gems
      - run:
          name: Run tests
          command: bundle exec rake test --trace

workflows:
  test:
    jobs:
      - rubocop:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          context: org-rubygems
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d{1,2}\.\d{1,2}\.\d{1,2}.*/
          requires:
            - rubocop
            - test
