version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - restore_cache:
          key: fluent-plugin-gelf2-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --full-index
      - save_cache:
          key: fluent-plugin-gelf2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: run tests
          command: bundle exec rake --trace

workflows:
  version: 2
  test:
    jobs:
      - test
