version: 2.1
executors:
  ruby:
    parameters:
      version:
        type: string
        default: latest
    docker:
      - image: circleci/ruby:<< parameters.version >>
    working_directory: ~/fluent-plugin-gelf
jobs:
  test:
    executor: ruby
    steps:
      - checkout
      - restore_cache:
          key: fluent-plugin-gelf2-{{ checksum "Gemfile.lock" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 --full-index
      - save_cache:
          key: fluent-plugin-gelf2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: run tests
          command: bundle exec rake --trace

workflows:
  test:
    jobs:
      - test
